### ISSUE TITLE
Does it have a VM or not?

### ISSUE THREAD

**Issue by Zireael07** [gamblevore/speedie#6]
README is more than a bit unclear on this point. 

If it doesn't, LuaJIT is a good fast VM to look at either as a target or as inspiration

**Comment by gamblevore** [comment]
Hello Zireael,

Apologies for the late reply. My email is sometimes slow.

Anyhow... I'm working on a VM right now. My VM will be done hopefully around january 2025. Soon!

The progress is going well and its quite far into the progress. Once the VM is done, I'll have to create a debugger too.

**Comment by Zireael07** [comment]
Thanks! Must've missed that second sentence as the README is pretty long
